//! A theme in the formats other software already reads.
//!
//! Each function returns plain data or text; writing files, setting
//! variables and answering D-Bus calls is the desktop's job.
//!
//! | Consumer | Function | How it is applied |
//! | --- | --- | --- |
//! | Apps that follow `org.freedesktop.appearance` (GTK 4/libadwaita, Qt 6.5+, Firefox, Chromium, Electron) | [`portal`] | Served by an `org.freedesktop.impl.portal.Settings` backend |
//! | GTK 3 and 4 settings (icons, cursor, font, dark preference) | [`gtk_settings`] | `$XDG_CONFIG_HOME/gtk-3.0/settings.ini` and `gtk-4.0/settings.ini` |
//! | Cursors in every toolkit | [`environment`] | Session environment, for example `systemctl --user set-environment` |
//! | Android apps under the Android translation layer | [`android_colors`] | `res/values/colors.xml` of the theme bridge, or its overlay |
//! | Anything else | [`json`] | Read from a file, for example `$XDG_RUNTIME_DIR/derisk/theme.json` |
//!
//! CSS, GTK style sheets and Qt style sheets are generated by `x2mcsapi`,
//! which also measures the components so foreign controls get their sizes.

use std::fmt::Write as _;

use crate::{Color, Scheme, Theme, Tokens};

/// The values of the `org.freedesktop.appearance` settings namespace.
///
/// A settings portal backend returns these from `Read`/`ReadAll` and emits
/// `SettingChanged` when the theme changes.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Portal {
    /// `color-scheme`: 1 prefers dark, 2 prefers light (0, no preference, is
    /// never sent because every theme has a scheme).
    pub color_scheme: u32,
    /// `accent-color`: sRGB channels in `0.0..=1.0`.
    pub accent_color: (f64, f64, f64),
    /// `contrast`: 1 asks apps for higher contrast, 0 for none.
    pub contrast: u32,
}

/// The freedesktop appearance settings for `theme`.
pub fn portal(theme: &Theme) -> Portal {
    let p = &theme.palette;
    // Straight from the bytes: going through f32 would print as
    // 0.1764705926179886 instead of 0.17647058823529413.
    let channel = |c: u8| f64::from(c) / 255.0;
    Portal {
        color_scheme: match theme.scheme {
            Scheme::Dark => 1,
            Scheme::Light => 2,
        },
        accent_color: (
            channel(p.accent.r),
            channel(p.accent.g),
            channel(p.accent.b),
        ),
        // WCAG AAA body text is 7:1; a theme that keeps even its borders at
        // that contrast is a high-contrast theme, and apps should follow.
        contrast: u32::from(p.border.contrast(p.background) >= 7.0),
    }
}

/// `text` without control characters, for line-based formats and the
/// environment. Theme files cannot contain them (the parser rejects them), but
/// a [`Theme`] built in code can, and one injected line in settings.ini is
/// enough to load a GTK module into every GTK app.
fn single_line(text: &str) -> String {
    text.chars().filter(|c| !c.is_control()).collect()
}

/// GTK font size in points from a size in logical pixels (96 per inch).
fn points(pixels: f32) -> f32 {
    (pixels * 0.75 * 2.0).round() / 2.0
}

/// `settings.ini` for GTK 3 and GTK 4: dark preference, icon and cursor
/// themes, and the interface font.
pub fn gtk_settings(theme: &Theme) -> String {
    format!(
        "[Settings]\n\
         gtk-application-prefer-dark-theme={dark}\n\
         gtk-icon-theme-name={icons}\n\
         gtk-cursor-theme-name={cursor}\n\
         gtk-cursor-theme-size={cursor_size}\n\
         gtk-font-name={font} {size}\n",
        dark = u8::from(theme.scheme == Scheme::Dark),
        icons = single_line(&theme.icons.theme),
        cursor = single_line(&theme.icons.cursor),
        cursor_size = theme.icons.cursor_size,
        font = single_line(&theme.fonts.sans),
        size = points(theme.fonts.size),
    )
}

/// Session environment variables the theme sets: the cursor theme and size,
/// which X11 and Wayland clients read through libXcursor and libwayland-cursor.
pub fn environment(theme: &Theme) -> [(&'static str, String); 2] {
    [
        ("XCURSOR_THEME", single_line(&theme.icons.cursor)),
        ("XCURSOR_SIZE", theme.icons.cursor_size.to_string()),
    ]
}

/// An Android color, `#aarrggbb`.
fn android(color: Color) -> String {
    format!(
        "#{:02x}{:02x}{:02x}{:02x}",
        color.a, color.r, color.g, color.b
    )
}

/// Every token with its name, in a stable order, for the exporters below.
fn named(t: &Tokens) -> [(&'static str, Color); 15] {
    [
        ("background", t.background),
        ("foreground", t.foreground),
        ("card", t.card),
        ("muted", t.muted),
        ("muted_foreground", t.muted_foreground),
        ("primary", t.primary),
        ("primary_foreground", t.primary_foreground),
        ("secondary", t.secondary),
        ("hover", t.hover),
        ("destructive", t.destructive),
        ("destructive_foreground", t.destructive_foreground),
        ("border", t.border),
        ("ring", t.ring),
        ("overlay", t.overlay),
        ("selection", t.selection),
    ]
}

/// Android color resources (`res/values/colors.xml`).
///
/// Every token is defined as `mcsapi_<role>`, and the colors AppCompat and
/// Material themes are built from (`colorPrimary`, `colorAccent`,
/// `colorSurface`, ...) are defined from those, so a theme overlay that
/// references them restyles apps without knowing mcsapi's names.
pub fn android_colors(theme: &Theme) -> String {
    let t = theme.tokens();
    let mut xml = String::from(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
         <!-- Generated by mcsapi-theme; edit the desktop theme instead. -->\n\
         <resources>\n",
    );
    for (name, color) in named(&t) {
        // Infallible: writing to a String cannot fail.
        let _ = writeln!(
            xml,
            "    <color name=\"mcsapi_{name}\">{}</color>",
            android(color)
        );
    }
    let material = [
        ("colorPrimary", "primary"),
        ("colorPrimaryDark", "background"),
        ("colorPrimaryVariant", "primary"),
        ("colorOnPrimary", "primary_foreground"),
        ("colorAccent", "primary"),
        ("colorSecondary", "primary"),
        ("colorOnSecondary", "primary_foreground"),
        ("colorBackground", "background"),
        ("colorOnBackground", "foreground"),
        ("colorSurface", "card"),
        ("colorOnSurface", "foreground"),
        ("colorError", "destructive"),
        ("colorOnError", "destructive_foreground"),
        ("colorControlNormal", "muted_foreground"),
        ("colorControlHighlight", "hover"),
        ("colorControlActivated", "primary"),
        ("colorButtonNormal", "secondary"),
        ("textColorPrimary", "foreground"),
        ("textColorSecondary", "muted_foreground"),
        ("textColorHighlight", "selection"),
        ("windowBackground", "background"),
        ("navigationBarColor", "background"),
        ("statusBarColor", "background"),
    ];
    for (name, role) in material {
        let _ = writeln!(
            xml,
            "    <color name=\"{name}\">@color/mcsapi_{role}</color>"
        );
    }
    xml.push_str("</resources>\n");
    xml
}

fn json_string(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if u32::from(c) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", u32::from(c));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// The theme and its derived tokens as JSON, for consumers in other
/// languages. Colors are `#rrggbb` or `#rrggbbaa` strings.
///
/// ```json
/// {"id":"derisk-dark","name":"Derisk Dark","scheme":"dark",
///  "palette":{"background":"#0f172a",...},
///  "tokens":{"background":"#0f172a",...,"radius":6},
///  "fonts":{"sans":"Ubuntu",...},"icons":{"theme":"Adwaita",...},
///  "portal":{"color_scheme":1,"accent_color":[0.64,0.9,0.21],"contrast":0}}
/// ```
pub fn json(id: &str, theme: &Theme) -> String {
    let p = &theme.palette;
    let t = theme.tokens();
    let f = &theme.fonts;
    let i = &theme.icons;
    let portal = portal(theme);
    let colors = |pairs: &[(&str, Color)]| {
        pairs
            .iter()
            .map(|(name, color)| format!("\"{name}\":\"{color}\""))
            .collect::<Vec<_>>()
            .join(",")
    };
    let palette = colors(&[
        ("background", p.background),
        ("surface", p.surface),
        ("foreground", p.foreground),
        ("border", p.border),
        ("accent", p.accent),
        ("destructive", p.destructive),
    ]);
    let tokens = colors(&named(&t));
    let (r, g, b) = portal.accent_color;
    format!(
        "{{\"id\":{id},\"name\":{name},\"scheme\":\"{scheme}\",\
         \"palette\":{{{palette}}},\
         \"tokens\":{{{tokens},\"radius\":{radius}}},\
         \"fonts\":{{\"sans\":{sans},\"sans_weight\":{weight},\"monospace\":{mono},\
         \"size\":{size},\"small_size\":{small},\"monospace_size\":{mono_size}}},\
         \"icons\":{{\"theme\":{icons},\"cursor\":{cursor},\"cursor_size\":{cursor_size}}},\
         \"portal\":{{\"color_scheme\":{color_scheme},\"accent_color\":[{r},{g},{b}],\
         \"contrast\":{contrast}}}}}\n",
        id = json_string(id),
        name = json_string(&theme.name),
        scheme = theme.scheme.as_str(),
        radius = t.radius,
        sans = json_string(&f.sans),
        weight = f.sans_weight,
        mono = json_string(&f.monospace),
        size = f.size,
        small = f.small_size,
        mono_size = f.monospace_size,
        icons = json_string(&i.theme),
        cursor = json_string(&i.cursor),
        cursor_size = i.cursor_size,
        color_scheme = portal.color_scheme,
        contrast = portal.contrast,
    )
}
