/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Desktop policy with fixed workspaces and globally unique windows.
 *
 * The host owns surfaces, input, and rendering; it maps window IDs to its own
 * surfaces and calls `remove` when a window is destroyed.
 */
export declare class Desktop {
  /** Creates workspaces ordered by ID and activates the first supplied ID. */
  constructor(workspaces: Array<number>)
  /** The active workspace's ID. */
  get activeWorkspace(): number
  /** Returns a snapshot of the active workspace. */
  active(): WorkspaceState
  /** Returns snapshots of every workspace in ID order. */
  workspaces(): Array<WorkspaceState>
  /** Returns the workspace containing a window, or `null` if it is unmanaged. */
  workspaceOf(window: number): number | null
  /** Adds a new window to the active workspace and focuses it. */
  insert(window: number): void
  /** Removes a window from any workspace, repairing focus if necessary. */
  remove(window: number): void
  /**
   * Moves a window to another workspace and focuses it there.
   *
   * The active workspace is unchanged.
   */
  moveWindow(window: number, workspace: number): void
  /** Activates an existing workspace, preserving each workspace's focus. */
  switchTo(workspace: number): void
  /** Focuses a member of the active workspace. */
  focus(window: number): void
  /** Cycles focus forward in the active workspace, wrapping at the end. */
  focusNext(): number | null
  /** Cycles focus backward in the active workspace, wrapping at the beginning. */
  focusPrevious(): number | null
  /** Promotes the focused window in the active workspace to the main pane. */
  promoteFocused(): void
  /** Changes the active workspace's layout. */
  setLayout(layout: Layout): void
  /**
   * Computes placements for the active workspace within the output bounds.
   *
   * Throws `InvalidGeometry` or `InsufficientSpace`.
   */
  arrange(bounds: Rect): Array<Placement>
}

/**
 * Computes placements for windows in the given order, without a desktop.
 *
 * Useful for previewing a layout or for hosts that track membership
 * themselves. Throws `InvalidGeometry` or `InsufficientSpace`.
 */
export declare function arrange(layout: Layout, bounds: Rect, windows: Array<number>): Array<Placement>

/** Simple xmonad-like tiling policies. */
export type Layout = 'tall' | 'monocle'

/** A window and its proposed logical geometry. */
export interface Placement {
  /** The window to configure. */
  window: number
  /** Bounds to apply through the host's configure/rendering path. */
  geometry: Rect
}

/** A rectangle in logical compositor coordinates, not physical pixels. */
export interface Rect {
  /** Left edge. */
  x: number
  /** Top edge. */
  y: number
  /** Width; must be positive for output bounds. */
  width: number
  /** Height; must be positive for output bounds. */
  height: number
}

/** A snapshot of one workspace. Changing it does not change the desktop. */
export interface WorkspaceState {
  /** Stable workspace identity. */
  id: number
  /** Windows in tiling order: the main window first, then the rest by ID. */
  windows: Array<number>
  /** The focused window, or `null` for an empty workspace. */
  focused: number | null
  /** The workspace's layout. */
  layout: Layout
  /** Whether this is the active workspace. */
  active: boolean
}
